[package]
name = "oria-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "oria"
path = "src/lib.rs"

[[bin]]
name = "oriac"
path = "src/bin/main.rs"

[dependencies]
pest = { version = "2.5.2", features = ["pretty-print"]}
pest_derive = { version = "2.5.2"}
clap = "4.0.29"